### ISSUE TITLE
Add welcome banner before parcel begins

### ISSUE THREAD

**Issue by mikedotexe** [nearprotocol/create-near-app#157]
Talking to @eriktrautman today, we want to make sure every developer knows what to expect after running the commands posted on the homepage. At the time of this writing, those commands are simply:

```
# Drop this in your CLI and run it
npx create-near-app your-awesome-project
cd your-awesome-project
yarn
yarn dev
```

Folks unfamiliar with local web development may be unfamiliar with opening links to a localhost site. Furthermore, those same folks may think that the script is still running since they don't see their normal terminal return to the expected prompt.

Solution: let's add some banner thats conveys that they've successfully got a NEAR app running and to open the localhost link in their browser of choice.

**Comment by vgrichina** [comment]
> Solution: let's add some banner thats conveys that they've successfully got a NEAR app running and to open the localhost link in their browser of choice.

there is currently such message:

```
Server running at http://localhost:1234 
✨  Built in 23.36s.
```

I'd argue if you cannot figure out what's going on (server got started, build completed), no kind of banner would help (much deeper education required).

As for opening browser, it's trivial to do with Parcel:
https://parceljs.org/cli.html#open-in-browser

**Comment by mikedotexe** [comment]
Laughed out loud. I don't think this is easy for everyone. From the Developer eXperience standpoint, it's our job to make this stuff super easy for folks. For example, we want CS 101 folks to be able to pick this up. Their classes are all about C++, not web. They may have never seen their Terminal "hang" like this before.
I'd hate to turn them away saying, "Sorry, Erik, you're just not cut out for this."

<img width="361" alt="Screenshot 2020-04-01 17 37 54" src="https://user-images.githubusercontent.com/1042667/78199387-66d22b00-7440-11ea-9c66-803c3a883697.png">

While it's not high priority, it's also not high effort and can only help.

**Comment by vgrichina** [comment]
> For example, we want CS 101 folks to be able to pick this up. Their classes are all about C++, not web.

My point is that they won't be able to pick our stuff up by seeing snippet and copy-pasting it. We won't help much by showing more prominent banner with the stuff that already is displayed.  

Impatient web devs and people just learning CS should be directed to different entry points altogether. Like right now if you even want to go through tutorials in docs (https://docs.nearprotocol.com/docs/tutorials/zero-to-hero) you need to have far more understanding of web stuff than CS 101. We don't even point folks to any resources allowing to learn basic web concepts required. So if we are any serious about this – effort has to be much bigger than a banner here.

**Comment by vgrichina** [comment]
I've checked create-react-app and I think it makes sense to do same stuff:
1) install dependencies automatically
2) show some basic instructions in console

https://github.com/nearprotocol/create-near-app/pull/186

**Comment by mikedotexe** [comment]
Linked PR looks good to me, feel free to merge and close. Or if there are other improvements, no rush

**Comment by vgrichina** [comment]
create-near-app 0.9.1 released
