### ISSUE TITLE
`noReact` option is not scalable

### ISSUE THREAD

**Issue by frol** [nearprotocol/create-near-app#2]
I have three topics here:

0. What do you think about using an existing tool for project templating? e.g. https://github.com/cookiecutter/cookiecutter

1. Let's not use unclear boolean options, i.e. if I specify that there should be NO React, then what is in there? Angular? Vue.js? Let's use some sort of "template name" option here, e.g. "empty" / "scratch" / "react" / ...

2. According to [yargs documentation](http://yargs.js.org/docs/), `no-` prefix is automatically generated for boolean options. Also, it is a best practice to use [kebab-case](http://wiki.c2.com/?KebabCase) for CLI options.

/cc @vgrichina @ilblackdragon

**Comment by icerove** [comment]
I will use 'plain' or 'vanilla' to replace 'no react' like I used to do that. If we can have more templates, we can give different name option for this. 
Why should we use cookiecutter? It is likely it is more friendly to the python based project and in our project, they are all use package.json.

**Comment by vgrichina** [comment]
0) Agree with @icerove we shouldn't bring in Python just to generate JS web app templates, that would degrade developer experience. We might use some JS templating stuff if we need more functionality. 
1) `--no-react` still would be my thinking for when I get react included by default (kinda e.g. how there is `--no-yarn` https://github.com/sindresorhus/np#usage). Maybe we should keep it as alias.
2) +1 on kebab-case

**Comment by frol** [comment]
0. I did not suggest using exactly the cookiecutter, I completely agree that bringing another language stack is unreasonable! My point was just to review if there are similar tools in JS world (I just don't know if there is any)
1. `--no-react` tells nothing about the intention of creating a vanilla JS project. Meh

Anyway, the original issue is resolved in https://github.com/nearprotocol/create-near-app/commit/3bd509ae5931e2627fe55f4a15ca02cc80e34147

**Comment by frol** [comment]
@icerove I would still consider using a non-boolean option for this vanilla/react types, e.g. `--type=...` / `--project-type=...` or `--stack=...` / `--project-stack=...` with the default value `react` if that is our default. This way, we will be consistent and will be able to add another option without a need to validate the boolean flags to be selected exclusively (e.g. `vanilla` is not compatible with `angular`).

**Comment by frol** [comment]
So, just for the reference, there are the following scaffolding projects:

* [`yeoman`](https://yeoman.io/) (aka `yo`) - implemented in JS
* [`ffizer`](https://github.com/ffizer/ffizer) - implemented in Rust, though the binary releases are only available for MacOS and Linux
* [Similar projects](https://cookiecutter.readthedocs.io/en/latest/readme.html#similar-projects)

**Comment by vgrichina** [comment]
@frol yo is horrible overkill for our purposes, I already looked into it.

There are few projects which look more useful, but what we are doing is still simple enough I feel. If we want to make something more flexible (e.g. Rails-like generators for every artifact, usable even after initial project creation) – more likely that some framework would be useful.

**Comment by frol** [comment]
@vgrichina It is good to know that someone has already evaluated the options. My point was to just don't reinvent the wheel. The current implementation is certainly simple, but in case it gets bigger, I would suggest we go with an existing solution.

**Comment by vgrichina** [comment]
> The current implementation is certainly simple, but in case it gets bigger, I would suggest we go with an existing solution.

@frol totally agree
