### ISSUE TITLE
Add startup script using near-shell dev-deploy

### ISSUE THREAD

**Issue by kcole16** [nearprotocol/create-near-app#59]
Version 0.20.0 of near-shell has `dev-deploy` ([PR](https://github.com/nearprotocol/near-shell/pull/240)), which combines the `create-account` and `deploy` steps by auto-generating an account.

We can add a startup script that reduces the number of steps to get the app up and running.

## Acceptance Criteria
- [ ] Startup script completes the following
  - [ ] Creates a new account
  - [ ] Updates `config.js` with account name
  - [ ] Deploys contract
  - [ ] Runs the frontend

**Comment by kcole16** [comment]
@icerove @vgrichina Thoughts?

**Comment by kcole16** [comment]
@icerove Pretty good example of this here: https://github.com/nearprotocol/near-chess/blob/master/package.json

**Comment by icerove** [comment]
finish
