### ISSUE TITLE
Build issue in example rust contract 

### ISSUE THREAD

**Issue by janedegtiareva** [nearprotocol/create-near-app#77]
Pulling out of https://github.com/nearprotocol/create-near-app/pull/65 comment thread to have
an easier-to-follow communication thread. 

  [I] ➜ ./build.sh 
   Compiling syn v1.0.5
   Compiling regex v1.3.1
./build.sh: line 4: 76741 Killed: 9               RUSTFLAGS='-C link-arg=-s' cargo build --target wasm32-unknown-unknown --release

npm ERR! code ELIFECYCLE
npm ERR! errno 137
npm ERR! blank-rust-proj-vg@0.0.1 build: `cd contract && ./build.sh`
npm ERR! Exit status 137
npm ERR! 
npm ERR! Failed at the blank-rust-proj-vg@0.0.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by janedegtiareva** [comment]
@vgrichina Do you mind trying the following?

`rm -rf tmp-project
rustup override set nightly
rustup target add wasm32-unknown-unknown
node index.js tmp_project --rust --vanilla
cd tmp_project/
yarn start `

**Comment by janedegtiareva** [comment]
If that doesn't work, could you also try to compile one of the rust contracts in near-bindgen?

**Comment by vgrichina** [comment]
> If that doesn't work, could you also try to compile one of the rust contracts in near-bindgen?

Contracts in near-bindgen also don’t compile with the same error 

@nearmax

**Comment by vgrichina** [comment]
```
create-near-app/blank-rust-proj-vg/contract on  blank-rust-proj [?] is 📦 vstatus-message:0.1.0 via 𝗥 v1.42.0 
[I] ➜ rustup override set nightly

info: using existing install for 'nightly-x86_64-apple-darwin'
info: override toolchain for '/Users/vg/Documents/create-near-app/blank-rust-proj-vg/contract' set to 'nightly-x86_64-apple-darwin'

  nightly-x86_64-apple-darwin unchanged - rustc 1.42.0-nightly (8a79d08fa 2020-01-27)


create-near-app/blank-rust-proj-vg/contract on  dev-deploy [!?] is 📦 vstatus-message:0.1.0 via 𝗥 v1.42.0 
[I] ➜ rustup target add wasm32-unknown-unknown

info: component 'rust-std' for target 'wasm32-unknown-unknown' is up to date
```

looks like stuff is already installed, I think I already did these during previous troubleshooting

**Comment by vgrichina** [comment]
@nearmax I wonder if I can be running into limitations of my machine. Like is there certain RAM requirement for compilation or smth? I have MacBook Air with only 16 GB of RAM.

**Comment by vgrichina** [comment]
Somehow it all worked out after retrying yet again today. Not sure what was the reason: my machine having more free resources, some crate being updated, etc.

**Comment by vgrichina** [comment]
@nearmax @janedegtiareva 

I feel that `rustup override set nightly` might be required, we need to document it in sample project then. Probably also makes sense to have `yarn clean` script or smth like that to clean all the `target/` stuff, etc for people who try first with wrong settings.

**Comment by janedegtiareva** [comment]
> Somehow it all worked out after retrying yet again today. Not sure what was the reason: my machine having more free resources, some crate being updated, etc.

Uh, it's not ideal when we don't know why something stopped breaking magically, but at least it works now. If this is no longer reproable, let's close the issue? We can reopen if the buggy behavior comes back.

**Comment by vgrichina** [comment]
@janedegtiareva I didn't try to repro by resetting Rust stuff and starting over.  Given that there is no `rustup override set nightly` in instructions, maybe there is still issue without it.

**Comment by mikedotexe** [comment]
@janedegtiareva I just tried going into `contract/rust` and running `./build.sh` and everything went smoothly. I did not specify nightly. I think this issue can be closed, but wanted to check in first.

**Comment by icerove** [comment]
done
