### ISSUE TITLE
Improve devx: remove manual step to fill in contract name in src/config.js

### ISSUE THREAD

**Issue by janedegtiareva** [nearprotocol/create-near-app#78]
Right now we have a manual step in a full stack example which prevents scripting the whole process from app creation all the way to app running.

**Comment by vgrichina** [comment]
`near dev-deploy` (see e.g. https://github.com/nearprotocol/create-near-app/pull/87) also to some extent addresses this problem as it means `yarn start` should work without any setup at all (`yarn deploy` would still need setup though).
