### ISSUE TITLE
didn't find .gitignore after `npx create-near-app --vanilla`

### ISSUE THREAD

**Issue by amgando** [nearprotocol/create-near-app#99]
seems strange since there's a `.gitignore` file in all the template folders?!

after running `npm test` and `npm run dev` i came up with these additions to a local `.gitignore` that i thought would make development less noisy

```
# ignore Mac OS noise
.DS_Store

# ignore large, hairy, autogenerated folders
node_modules/

# ignore Wasm output generated by build process
out/

# ignore accounts generated by tests
neardev/shared-test/*
# but not the original test.near.json account
!neardev/shared-test/test.near.json

# ignore any default network private keys and dev-account
neardev/default/*
neardev/dev-account

# ignore dev .cache
.cache/

# ignore dist folder generated by build process
dist/
```

**Comment by mikedotexe** [comment]
Yes, I think this is kind of a big deal. I don't want new folks to accidentally commit and revision their `neardev` folder, for instance.
Opened this PR to address this: https://github.com/nearprotocol/create-near-app/pull/67
The reason why this happens is explained in that PR, but basically when you publish an npm package, it removes the `.gitignore` files. So the solution is the package a `near.gitignore` file and rename it during project creation.

**Comment by mikedotexe** [comment]
Closing as this was addressed in the above-mentioned PR
